export const DEFAULT_EXPENSE_CATEGORIES = [
  'Food & Dining',
  'Transport',
  'Groceries',
  'Bills',
  'Entertainment',
] as const;

export const DEFAULT_INCOME_CATEGORIES = [
  'Salary',
  'Freelance',
] as const;

export const UNCATEGORIZED_EXPENSE_LABEL = 'Uncategorized Expense';
export const UNCATEGORIZED_INCOME_LABEL = 'Uncategorized Income';
export const UNCATEGORIZED_LABEL = UNCATEGORIZED_EXPENSE_LABEL;
export const DEFAULT_WALLET_ID = 1;

export const EXTERNAL_API_PRESETS: Record<
  string,
  { label: string; url: string; model: string; requiresKey: boolean }
> = {
  openai: {
    label: 'OpenAI',
    url: 'https://api.openai.com/v1',
    model: 'gpt-4o-mini',
    requiresKey: true,
  },
  deepseek: {
    label: 'DeepSeek',
    url: 'https://api.deepseek.com/v1',
    model: 'deepseek-chat',
    requiresKey: true,
  },
  groq: {
    label: 'Groq',
    url: 'https://api.groq.com/openai/v1',
    model: 'llama-3.3-70b-versatile',
    requiresKey: true,
  },
  ollama: {
    label: 'Ollama (Local)',
    url: 'http://10.0.2.2:11434/v1',
    model: 'qwen2.5:3b',
    requiresKey: false,
  },
  together: {
    label: 'Together AI',
    url: 'https://api.together.xyz/v1',
    model: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    requiresKey: true,
  },
  custom: {
    label: 'Custom / Self-Hosted',
    url: 'https://api.example.com/v1',
    model: 'custom-model',
    requiresKey: false,
  },
};

import type { ModelCatalogEntry } from './types';

export const MODEL_CATALOG: Record<string, ModelCatalogEntry> = {
  'qwen3.5-0.8b': {
    id: 'qwen3.5-0.8b',
    displayName: 'Qwen 3.5 0.8B',
    family: 'qwen',
    parameterSize: '0.8B',
    quantization: 'Q4_K_M',
    capabilities: ['text'],
    fileName: 'Qwen3.5-0.8B-Q4_K_M.gguf',
    downloadUrl: 'https://huggingface.co/unsloth/Qwen3.5-0.8B-GGUF/resolve/main/Qwen3.5-0.8B-Q4_K_M.gguf',
    sha256: '',
    fileSizeBytes: 622997000,
    minFreeSpaceBytes: 1024 * 1024 * 1024,
    recommendedRamBytes: 2 * 1024 * 1024 * 1024,
    requiredRamBytes: 1.5 * 1024 * 1024 * 1024,
    description: 'Ultra-lightweight text model. Excellent for basic receipt parsing.',
  },
  'qwen3.5-2b': {
    id: 'qwen3.5-2b',
    displayName: 'Qwen 3.5 2B',
    family: 'qwen',
    parameterSize: '2B',
    quantization: 'Q4_K_M',
    capabilities: ['text'],
    fileName: 'Qwen3.5-2B-Q4_K_M.gguf',
    downloadUrl: 'https://huggingface.co/unsloth/Qwen3.5-2B-GGUF/resolve/main/Qwen3.5-2B-Q4_K_M.gguf',
    sha256: '',
    fileSizeBytes: 1503238000,
    minFreeSpaceBytes: 2 * 1024 * 1024 * 1024,
    recommendedRamBytes: 3 * 1024 * 1024 * 1024,
    requiredRamBytes: 2 * 1024 * 1024 * 1024,
    description: 'Balanced text model. Good mix of speed and conversational ability.',
  },
  'qwen3.5-4b': {
    id: 'qwen3.5-4b',
    displayName: 'Qwen 3.5 4B',
    family: 'qwen',
    parameterSize: '4B',
    quantization: 'Q4_K_M',
    capabilities: ['text'],
    fileName: 'Qwen3.5-4B-Q4_K_M.gguf',
    downloadUrl: 'https://huggingface.co/unsloth/Qwen3.5-4B-GGUF/resolve/main/Qwen3.5-4B-Q4_K_M.gguf',
    sha256: '',
    fileSizeBytes: 3232049000,
    minFreeSpaceBytes: 4 * 1024 * 1024 * 1024,
    recommendedRamBytes: 6 * 1024 * 1024 * 1024,
    requiredRamBytes: 4 * 1024 * 1024 * 1024,
    description: 'High performance text model. Needs a newer device with high RAM.',
  },
  'qwen3.5-9b': {
    id: 'qwen3.5-9b',
    displayName: 'Qwen 3.5 9B',
    family: 'qwen',
    parameterSize: '9B',
    quantization: 'Q4_K_M',
    capabilities: ['text'],
    fileName: 'Qwen3.5-9B-Q4_K_M.gguf',
    downloadUrl: 'https://huggingface.co/unsloth/Qwen3.5-9B-GGUF/resolve/main/Qwen3.5-9B-Q4_K_M.gguf',
    sha256: '',
    fileSizeBytes: 6625662000,
    minFreeSpaceBytes: 8 * 1024 * 1024 * 1024,
    recommendedRamBytes: 10 * 1024 * 1024 * 1024,
    requiredRamBytes: 8 * 1024 * 1024 * 1024,
    description: 'Flagship text model. Very heavy, only for flagship devices.',
  },
  'gemma4-e2b-it': {
    id: 'gemma4-e2b-it',
    displayName: 'Gemma 4 E2B Instruct',
    family: 'gemma',
    parameterSize: 'E2B',
    quantization: 'Q4_K_M',
    capabilities: ['text', 'multimodal'],
    fileName: 'gemma-4-E2B-it-Q4_K_M.gguf',
    downloadUrl: 'https://huggingface.co/unsloth/gemma-4-E2B-it-GGUF/resolve/main/gemma-4-E2B-it-Q4_K_M.gguf',
    sha256: '',
    fileSizeBytes: 3110000000,
    minFreeSpaceBytes: 4 * 1024 * 1024 * 1024,
    recommendedRamBytes: 6 * 1024 * 1024 * 1024,
    requiredRamBytes: 4 * 1024 * 1024 * 1024,
    description: 'Multimodal model (Text + Image). Edge-optimized architecture.',
  },
  'gemma4-e4b-it': {
    id: 'gemma4-e4b-it',
    displayName: 'Gemma 4 E4B Instruct',
    family: 'gemma',
    parameterSize: 'E4B',
    quantization: 'Q4_K_M',
    capabilities: ['text', 'multimodal'],
    fileName: 'gemma-4-E4B-it-Q4_K_M.gguf',
    downloadUrl: 'https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/gemma-4-E4B-it-Q4_K_M.gguf',
    sha256: '',
    fileSizeBytes: 4980000000,
    minFreeSpaceBytes: 6 * 1024 * 1024 * 1024,
    recommendedRamBytes: 8 * 1024 * 1024 * 1024,
    requiredRamBytes: 6 * 1024 * 1024 * 1024,
    description: 'Advanced Multimodal model. High accuracy, heavy footprint.',
  },
};

export const DEFAULT_APP_SETTINGS = {
  themeMode: 'system',
  currencyCode: 'IDR',
  useThousandsSeparator: true,
  dateFormat: 'en-GB',
  showIncomeInReportsFirst: false,
  fontScale: 1,
  aiInferenceMode: 'local',
  activeModelId: 'qwen3.5-2b',
  ocrEngineId: 'mlkit',
  aiWifiOnlyDownload: false,
  externalApiProvider: 'openai',
  externalApiUrl: 'https://api.openai.com/v1',
  externalApiModel: 'gpt-4o-mini',
  externalApiKey: '',
  externalApiCustomHeaders: '{}',
  localSystemPrompt: '',
  externalSystemPrompt: '',
} as const;

export const APP_SETTING_KEYS = {
  themeMode: 'themeMode',
  currencyCode: 'currencyCode',
  useThousandsSeparator: 'useThousandsSeparator',
  dateFormat: 'dateFormat',
  showIncomeInReportsFirst: 'showIncomeInReportsFirst',
  fontScale: 'fontScale',
  aiInferenceMode: 'aiInferenceMode',
  activeModelId: 'activeModelId',
  ocrEngineId: 'ocrEngineId',
  aiWifiOnlyDownload: 'aiWifiOnlyDownload',
  externalApiProvider: 'externalApiProvider',
  externalApiUrl: 'externalApiUrl',
  externalApiModel: 'externalApiModel',
  externalApiKey: 'externalApiKey',
  externalApiCustomHeaders: 'externalApiCustomHeaders',
  localSystemPrompt: 'localSystemPrompt',
  externalSystemPrompt: 'externalSystemPrompt',
} as const;
